name: CI
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Run Hardhat Tests
        run: yarn hardhat test

  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        with:
          fail-on: medium
          slither-args: --exclude-dependencies
