name: Deploy Serverless

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install serverless globally
        run: npm install -g serverless

      - name: Install dependencies
        run: yarn install
        working-directory: defender

      - name: Deploy to Defender
        env:
          DEFENDER_API_KEY: ${{ secrets.DEFENDER_API_KEY }}
          DEFENDER_API_SECRET: ${{ secrets.DEFENDER_API_SECRET }}
        run: serverless deploy --stage arbitrum
        working-directory: defender
